import Head from 'next/head'
import Image from 'next/image'
import Avatar from '../components/Avatar'
import { ViewGridIcon, MicrophoneIcon } from '@heroicons/react/solid'
import { SearchIcon } from '@heroicons/react/outline'
import Footer from '../components/Footer'
import { useRef } from 'react'
import useRouter from 'next/router'
export default function Home() {
  const router = useRouter;
  const searchInputRef = useRef(null)

  const search = (e) => {
    e.preventDefault();
    const term = searchInputRef.current.value;
    if (!term) return;
    router.push(`/search?term=${term}`)
  }
  return (
    <div className="flex flex-col justify-center h-screen">
      <Head>
        <title>Google clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <header className="flex w-full p-5 justify-between text-sm text-gray-700">
        {/* header left */}
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>
        {/* header-right */}
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Image</p>
          <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-200 cursor-pointer" />

          <Avatar url='https://firebasestorage.googleapis.com/v0/b/aman-instagram-52add.appspot.com/o/posts%2FsW1aGs2BwhAtWOZWW0MQ%2Fimage?alt=media&token=cb1a64ae-7ecd-40de-83d8-fdd37e0de0c3' />
        </div>
      </header>

      <form className="flex flex-col items-center mt-44 flex-grow w-4/5">
        <Image
          src="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png" alt="picture"
          width={300} height={100} />
        <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-xl max-w-md rounded-full border 
        border-gray-200 px-4 py-3 items-center sm:max-w-xl lg:max-w-2xl">
          <SearchIcon className="h-5 mr-3 text-gray-500" />
          <input ref={searchInputRef} className=" focus:outline-none flex-grow" type="text" />
          <MicrophoneIcon className="h-5" />
        </div>
        <div className="flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:flex-row sm:space-x-4">
          <button onClick={search} className="btn" >Search google</button>
          <button onClick={search} className="btn" >I'm feeling good</button>
        </div>
      </form>

      <Footer />
    </div>
  )
}
